version: '3'
services:
    web:
        build: .
        ports:
            - "3000:3000"
        stdin_open: true
        volumes:
            - /my-app-name/public/
            - ./my-app-name/public:/my-app-name/public
            - ./my-app-name/src:/my-app-name/src