version: '3'
services: 
    web:
        build:
            context: .
            dockerfile: ./Dockerfile
        command: npm start
        volumes: 
            - './:/my-app-name'
            - '/my-app-name/node_modules'
        stdin_open: true
        ports:
            - 3000:3000